### ISSUE TITLE
Authorization support

### ISSUE THREAD

**Issue by Nuanda** [Nuanda/plankrk#60]
If #58 is merged we need to add authorization. In this case it should be not possible to create a new Discussion for a non-user.

@mkasztelnik I assign this to you since you have experience with setting up auth systems.

**Comment by mkasztelnik** [comment]
I see following solutions:
  - custom made - it can be a way to go if authorization will be very simple
  - [cancancan](https://github.com/CanCanCommunity/cancancan) - cancan successor - we already know how to deal with it.
  - [pundit](https://github.com/elabs/pundit) - has much less magic than cancan. Currently more popular than cancan
  - [six](https://github.com/randx/six) - not so popular - used in gitlab

**Comment by mkasztelnik** [comment]
[Here](http://blog.railsapps.org/post/89153599310/rails-authorization-with-pundit) is a good comparation between cancan and pundit.

**Comment by Nuanda** [comment]
Well, I guess we will need the following auth functionality:
 - checking for user session existence (registered, logged in user)
 - filtering by user id (e.g. allowing to edit user's own comments).

Eventually we will probably, sooner or later, require admin login. However, I don't see this as strict requirement for role based auth: simple boolean flag should be enough.

Currently I don't see any need for other roles or user groups etc.

**Comment by mkasztelnik** [comment]
I was validating `pundit`, but in plankrk we will have relative simple authorization rules - that is why I prefer `cancancan` in this case. I should be able finish `cancancan` integration with simple discussion destroy action by tomorrow... ups today.
